/obj/effect/spawner/random/outpost_loot
	name = "outpost loot spawner"
	icon_state = "cash"
	spawn_loot_count = 1
	loot = list(
		/obj/item/spacecash/bundle/c1 = 10,
		/obj/item/spacecash/bundle/c10 = 5,
		/obj/item/spacecash/bundle/c20 = 3,
		/obj/item/spacecash/bundle/c50 = 2,
		/obj/item/spacecash/bundle/c100 = 1,
		/obj/item/clothing/head/kitty = 1,
		/obj/effect/spawner/costume/mafia = 1,
		/obj/effect/spawner/costume/mafia/white = 1,
		/obj/effect/spawner/costume/mafia/checkered = 1,
		/obj/effect/spawner/costume/mafia/beige = 1,
		/obj/item/flashlight/lamp = 1,
		/obj/item/flashlight/lamp/green = 1,
		/obj/item/flashlight/lantern = 1,
		/obj/item/passport = 1,
		/obj/item/passport/temporary = 1,
		/obj/item/passport/temporary/diplomat = 1,
		/obj/item/passport/solgov = 1,
		/obj/item/passport/cobrastan = 1,
		/obj/item/storage/fancy/ringbox/diamond = 1,
		/obj/item/storage/fancy/ringbox/silver = 1,
		/obj/item/clothing/under/dress/flower = 1,
		/obj/item/clothing/under/dress/wedding = 1,
		/obj/item/clothing/under/dress/wedding/orange = 1,
		/obj/item/clothing/under/dress/wedding/purple = 1,
		/obj/item/clothing/under/dress/wedding/blue = 1,
		/obj/item/clothing/under/dress/wedding/red = 1,
		/obj/item/clothing/head/centhat = 1,
		/obj/item/clothing/head/centcom_cap = 1,
		/obj/item/clothing/head/that = 1,
		/obj/item/clothing/head/nursehat = 1,
		/obj/item/clothing/head/snowman = 1,
		/obj/item/clothing/head/pirate = 1,
		/obj/item/clothing/head/pirate/captain = 1,
		/obj/item/clothing/head/bandana = 1,
		/obj/item/clothing/head/bearpelt = 1,
		/obj/item/clothing/head/fedora = 1,
		/obj/item/clothing/head/fedora/white = 1,
		/obj/item/clothing/head/fedora/beige = 1,
		/obj/item/clothing/head/flatcap = 1,
		/obj/item/clothing/head/hunter = 1,
		/obj/item/clothing/head/cone = 1,
		/obj/item/clothing/head/santa = 1,
		/obj/item/clothing/head/rice_hat = 1,
		/obj/item/clothing/head/papersack = 1,
		/obj/item/clothing/head/papersack/smiley = 1,
		/obj/item/clothing/head/crown = 1,
		/obj/item/clothing/head/frenchberet = 1,
		/obj/item/clothing/head/intern = 1,
		/obj/item/clothing/head/maidheadband = 1,
		/obj/item/clothing/head/cowboy = 1,
		/obj/item/clothing/head/franks_hat = 1,
		/obj/item/clothing/head/sunhat = 1,
		/obj/item/clothing/suit/bluetag = 1,
		/obj/item/clothing/suit/redtag = 1,
		/obj/item/clothing/suit/pirate = 1,
		/obj/item/clothing/suit/pirate/captain = 1,
		/obj/item/clothing/suit/judgerobe = 1,
		/obj/item/clothing/suit/apron/purple_bartender = 1,
		/obj/item/clothing/suit/toggle/owlwings = 1,
		/obj/item/clothing/suit/toggle/owlwings/griffinwings = 1,
		/obj/item/clothing/suit/cardborg = 1,
		/obj/item/clothing/suit/snowman = 1,
		/obj/item/clothing/suit/hooded/carp_costume = 1,
		/obj/item/clothing/suit/hooded/bloated_human = 1,
		/obj/item/clothing/suit/cybersun = 1,
		/obj/item/clothing/suit/straight_jacket = 1,
		/obj/item/clothing/suit/ianshirt = 1,
		/obj/item/clothing/suit/nerdshirt = 1,
		/obj/item/clothing/suit/jacket = 1,
		/obj/item/clothing/suit/jacket/leather = 1,
		/obj/item/clothing/suit/jacket/leather/duster = 1,
		/obj/item/clothing/suit/jacket/leather/duster/command = 1,
		/obj/item/clothing/suit/jacket/miljacket = 1,
		/obj/item/clothing/suit/jacket/letterman = 1,
		/obj/item/clothing/suit/jacket/letterman_red = 1,
		/obj/item/clothing/suit/jacket/letterman_syndie = 1,
		/obj/item/clothing/suit/jacket/letterman_warra = 1,
		/obj/item/clothing/suit/gothcoat = 1,
		/obj/item/clothing/suit/caution = 1,
		/obj/item/clothing/suit/hooded/ablative = 1,	// Под вопросом
		/obj/item/clothing/suit/ghost_sheet = 1,
		/obj/item/clothing/suit/toggle/suspenders/blue = 1,
		/obj/item/clothing/suit/toggle/suspenders/gray = 1,
		/obj/item/clothing/suit/hawaiian = 1,
		/obj/item/clothing/suit/hawaiian/pink = 1,
		/obj/item/clothing/suit/hawaiian/red = 1
	)

/obj/effect/spawner/random/outpost_loot/big
	name = "outpost big loot spawner"
	spawn_loot_count = 3

/obj/effect/spawner/random/celadon_drink
	name = "random drink spawner"
	desc = "Spawns a random drink with reagent."
	spawn_loot_count = 1
	loot = list(/obj/item/reagent_containers/food/drinks/drinkingglass = 1)

	var/list/possible_reagents = list(
		/datum/reagent/consumable/ethanol/beer,
		/datum/reagent/consumable/ethanol/wine,
		/datum/reagent/consumable/coffee,
		/datum/reagent/consumable/tea,
		/datum/reagent/consumable/ethanol/synthanol,
		/datum/reagent/consumable/ethanol/synthanol/robottears,
		/datum/reagent/consumable/ethanol/synthanol/trinary,
		/datum/reagent/consumable/ethanol/synthanol/servo,
		/datum/reagent/consumable/ethanol/synthanol/uplink,
		/datum/reagent/consumable/ethanol/synthanol/synthnsoda,
		/datum/reagent/consumable/ethanol/synthanol/synthignon,
		/datum/reagent/consumable/ethanol/bacchus_blessing,
		/datum/reagent/consumable/ethanol/amnesia,
		/datum/reagent/consumable/ethanol/suicider,
		/datum/reagent/consumable/orangejuice,
		/datum/reagent/consumable/tomatojuice,
		/datum/reagent/consumable/limejuice,
		/datum/reagent/consumable/carrotjuice,
		/datum/reagent/consumable/berryjuice,
		/datum/reagent/consumable/applejuice,
		/datum/reagent/consumable/watermelonjuice,
		/datum/reagent/consumable/lemonjuice,
		/datum/reagent/consumable/banana,
		/datum/reagent/consumable/milk,
		/datum/reagent/consumable/soymilk,
		/datum/reagent/consumable/cream,
		/datum/reagent/consumable/coffee,
		/datum/reagent/consumable/tea,
		/datum/reagent/consumable/icecoffee,
		/datum/reagent/consumable/icetea,
		/datum/reagent/consumable/space_cola,
		/datum/reagent/consumable/crosstalk,
		/datum/reagent/consumable/comet_trail,
		/datum/reagent/consumable/tadrixx,
		/datum/reagent/consumable/space_up,
		/datum/reagent/consumable/molten,
		/datum/reagent/consumable/lemon_lime,
		/datum/reagent/consumable/pacfuel,
		/datum/reagent/consumable/shoal_punch,
		/datum/reagent/consumable/sodawater,
		/datum/reagent/consumable/tonic,
		/datum/reagent/consumable/xeno_energy,
		/datum/reagent/consumable/ice,
		/datum/reagent/consumable/hot_coco,
		/datum/reagent/consumable/ethanol/beer,
		/datum/reagent/consumable/ethanol/kahlua,
		/datum/reagent/consumable/ethanol/whiskey,
		/datum/reagent/consumable/ethanol/vodka,
		/datum/reagent/consumable/ethanol/gin,
		/datum/reagent/consumable/ethanol/rum,
		/datum/reagent/consumable/ethanol/tequila,
		/datum/reagent/consumable/ethanol/vermouth,
		/datum/reagent/consumable/ethanol/wine,
		/datum/reagent/consumable/ethanol/absinthe,
		/datum/reagent/consumable/ethanol/hooch,
		/datum/reagent/consumable/ethanol/ale,
		/datum/reagent/consumable/ethanol/champagne,
		/datum/reagent/consumable/ethanol/sake,
		/datum/reagent/consumable/ethanol/fernet,
		/datum/reagent/consumable/ethanol/gintonic,
		/datum/reagent/consumable/ethanol/rum_coke,
		/datum/reagent/consumable/ethanol/cuba_libre,
		/datum/reagent/consumable/ethanol/whiskey_cola,
		/datum/reagent/consumable/ethanol/martini,
		/datum/reagent/consumable/ethanol/vodkamartini,
		/datum/reagent/consumable/ethanol/white_russian,
		/datum/reagent/consumable/ethanol/screwdrivercocktail,
		/datum/reagent/consumable/ethanol/bloody_mary,
		/datum/reagent/consumable/ethanol/brave_bull,
		/datum/reagent/consumable/ethanol/tequila_sunrise,
		/datum/reagent/consumable/ethanol/toxins_special,
		/datum/reagent/consumable/ethanol/beepsky_smash,
		/datum/reagent/consumable/ethanol/irish_cream,
		/datum/reagent/consumable/ethanol/manly_dorf,
		/datum/reagent/consumable/ethanol/longislandicedtea,
		/datum/reagent/consumable/ethanol/moonshine,
		/datum/reagent/consumable/ethanol/b52,
		/datum/reagent/consumable/ethanol/irishcoffee,
		/datum/reagent/consumable/ethanol/margarita,
		/datum/reagent/consumable/ethanol/black_russian,
		/datum/reagent/consumable/ethanol/manhattan,
		/datum/reagent/consumable/ethanol/whiskeysoda,
		/datum/reagent/consumable/ethanol/antifreeze,
		/datum/reagent/consumable/ethanol/barefoot,
		/datum/reagent/consumable/ethanol/snowwhite,
		/datum/reagent/consumable/ethanol/demonsblood,
		/datum/reagent/consumable/ethanol/devilskiss,
		/datum/reagent/consumable/ethanol/vodkatonic,
		/datum/reagent/consumable/ethanol/ginfizz,
		/datum/reagent/consumable/ethanol/bahama_mama,
		/datum/reagent/consumable/ethanol/singulo,
		/datum/reagent/consumable/ethanol/sbiten,
		/datum/reagent/consumable/ethanol/red_mead,
		/datum/reagent/consumable/ethanol/mead,
		/datum/reagent/consumable/ethanol/iced_beer,
		/datum/reagent/consumable/ethanol/grog,
		/datum/reagent/consumable/ethanol/aloe,
		/datum/reagent/consumable/ethanol/andalusia,
		/datum/reagent/consumable/ethanol/alliescocktail,
		/datum/reagent/consumable/ethanol/acid_spit,
		/datum/reagent/consumable/ethanol/amasec,
		/datum/reagent/consumable/ethanol/changelingsting,
		/datum/reagent/consumable/ethanol/irishcarbomb,
		/datum/reagent/consumable/ethanol/syndicatebomb,
		/datum/reagent/consumable/ethanol/hiveminderaser,
		/datum/reagent/consumable/ethanol/erikasurprise,
		/datum/reagent/consumable/ethanol/driestmartini,
		/datum/reagent/consumable/ethanol/bananahonk,
		/datum/reagent/consumable/ethanol/silencer,
		/datum/reagent/consumable/ethanol/drunkenblumpkin,
		/datum/reagent/consumable/ethanol/whiskey_sour,
		/datum/reagent/consumable/ethanol/hearty_punch,
		/datum/reagent/consumable/ethanol/atomicbomb,
		/datum/reagent/consumable/ethanol/gargle_blaster,
		/datum/reagent/consumable/ethanol/neurotoxin,
		/datum/reagent/consumable/ethanol/hippies_delight,
		/datum/reagent/consumable/ethanol/eggnog,
		/datum/reagent/consumable/ethanol/quadruple_sec,
		/datum/reagent/consumable/ethanol/quintuple_sec,
		/datum/reagent/consumable/ethanol/grasshopper,
		/datum/reagent/consumable/ethanol/stinger,
		/datum/reagent/consumable/ethanol/bastion_bourbon,
		/datum/reagent/consumable/ethanol/squirt_cider,
		/datum/reagent/consumable/ethanol/fringe_weaver,
		/datum/reagent/consumable/ethanol/sugar_rush,
		/datum/reagent/consumable/ethanol/crevice_spike,
		/datum/reagent/consumable/ethanol/peppermint_patty,
		/datum/reagent/consumable/ethanol/alexander,
		/datum/reagent/consumable/ethanol/amaretto_alexander,
		/datum/reagent/consumable/ethanol/sidecar,
		/datum/reagent/consumable/ethanol/between_the_sheets,
		/datum/reagent/consumable/ethanol/kamikaze,
		/datum/reagent/consumable/ethanol/mojito,
		/datum/reagent/consumable/ethanol/moscow_mule,
		/datum/reagent/consumable/ethanol/fernet_cola,
		/datum/reagent/consumable/ethanol/fanciulli,
		/datum/reagent/consumable/ethanol/branca_menta,
		/datum/reagent/consumable/ethanol/blank_paper,
		/datum/reagent/consumable/ethanol/wizz_fizz,
		/datum/reagent/consumable/ethanol/bug_spray,
		/datum/reagent/consumable/ethanol/jack_rose,
		/datum/reagent/consumable/ethanol/turbo,
		/datum/reagent/consumable/ethanol/old_timer,
		/datum/reagent/consumable/ethanol/rubberneck,
		/datum/reagent/consumable/ethanol/duplex,
		/datum/reagent/consumable/ethanol/trappist,
		/datum/reagent/consumable/ethanol/blazaam,
		/datum/reagent/consumable/ethanol/mauna_loa,
		/datum/reagent/consumable/ethanol/painkiller,
		/datum/reagent/consumable/ethanol/pina_colada,
		/datum/reagent/consumable/ethanol/pruno,
		/datum/reagent/consumable/ethanol/ginger_amaretto,
		/datum/reagent/consumable/ethanol/godfather,
		/datum/reagent/consumable/ethanol/godmother,
		/datum/reagent/consumable/ethanol/mudders_milk,
		/datum/reagent/consumable/ethanol/spriters_bane,
		/datum/reagent/consumable/ethanol/freezer_burn,
		/datum/reagent/consumable/ethanol/out_of_touch,
		/datum/reagent/consumable/ethanol/darkest_chocolate,
		/datum/reagent/consumable/ethanol/out_of_lime,
		/datum/reagent/consumable/ethanol/shotinthedark,
		/datum/reagent/consumable/ethanol/bullethell,
		/datum/reagent/consumable/ethanol/homesick
	)

	var/glass_type = /obj/item/reagent_containers/food/drinks/drinkingglass
	var/reagent_amount = 50

/obj/effect/spawner/random/celadon_drink/make_item(spawn_loc, type_path_to_make)
	var/obj/item/reagent_containers/glass = new glass_type(spawn_loc)
	var/reagent_type = pick(possible_reagents)
	glass.reagents.add_reagent(reagent_type, reagent_amount)
	return glass
